version: "3"
services:
  web:
    build: .  # Path to the directory containing your FastAPI application
    ports:
      - "${PORT}:${PORT}"  # Map the host port to the container port
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT}

  
